### PR TITLE
[NEW FEATURE] Tags (now works)

### PR DESCRIPTION
**Pull request by Huaraz2**
Hi
This will pull in my rebase pr #147.  I have made a tag feature and you can now pull it in if you wish as you can create and push tags to origin/upstream correctly

Creating tags dialog box:
image

pushing tags dialog box:
image

### CODE REVIEW

**Comment by andrebellafronte** [comment]
Great feature!

**Comment by Huaraz2** [comment]
@andrebellafronte thanks, as you can see from my last commit, it all works now :smiling_imp:

**Comment by davidak** [comment]
This is the only feature missing for me to replace SourceTree. :)

@Huaraz2 can you default the ref to last commit?

**Comment by Huaraz2** [comment]
> @Huaraz2 can you default the ref to last commit?

@davidak I think that it should automatically do this if you don't enter a commit ref

**Comment by davidak** [comment]
@Huaraz2 good. i only saw the screenshot.

@jacogr thanks for merging! will try it when it's released.

**Comment by jacogr** [comment]
@davidak I pushed a release today.

**Pull request merged**
