### PR TITLE
Better indication of diff changes

### PR DESCRIPTION
**Pull request by imperez**
I love the Diff view but it wasn't completely obvious what changed. So I updated the styles to highlight the line background instead so now the added/deleted lines now pop out much better.

### CODE REVIEW

**Comment by MarcelMue** [comment]
I agree that the changed lines are easier to notice, but atleast in my setup the text of the change got harder to read. Here are some images comparing before and after the pull request,
Before:

before

After:

after

On my setup the text with red background is hard to read, I am open for comments or different opinions though.

**Comment by pradyun** [comment]
You might want to use transparency for better results (See https://github.com/jacogr/atom-lcov-info).

**Comment by MarcelMue** [comment]
This could be a good idea, I will try it later on with

`background-color: fade(@text-color-error,50%);`

**Comment by pradyun** [comment]
:+1:

**Comment by MarcelMue** [comment]
@pradyun I tried this change a couple of days ago but fading the text color does not work as expected. Only some parts of the background get faded while others stay the same. I will focus on other issues for now, but feel free to experient yourself.

**Comment by MarcelMue** [comment]
Closed for now, further discussion should happen in an issue.

**Pull request closed without merging**
