### PR TITLE
Multi project

### PR DESCRIPTION
**Pull request by rdcklinux**
add multi project feature

### CODE REVIEW

**Comment by alexandernst** [comment]
+1 for this. Is this ready to be merged or is there something that needs to be polished?

**Comment by MarcelMue** [comment]
I looked at this briefly, it looks good to be merged but I have some exams currently and didn't find the time yet to test extensively. If you want to test it and report back I would greatly appreciate it :+1:

**Comment by MarcelMue** [comment]
I looked at this more intensely, some minor merge problems are there currently but I tried that locally and removing them isn't a big issue. Another problem that needs to be adressed is that currently the error message for "No repository found" does not work. Changing the git-control-view.coffe to this:
```
      if !git.isInitialised()

      git.alert "> This project is not a git repository. Either open another project or create a repository."

      else

      @setWorkspaceTitle(git.getRepository().path.split('/').reverse()[1])```

schould do the trick.

**Comment by rdcklinux** [comment]
fix on new branch

**Pull request closed without merging**
