### PR TITLE
You can choose the remote and the branch to push on

### PR DESCRIPTION
**Pull request by nounoursheureux**
2015-04-29-155936_1440x900_scrot

### CODE REVIEW

**Comment by MarcelMue** [comment]
Can you add a screenshot to show what has changed, I will have time to look at it in 30 minutes or so :)

**Comment by MarcelMue** [comment]
I had a look at your Pull Request now. 
Your code looks good and the implementation works fine as far as I can tell. I can see how this addition is very helpfull especially for working accross forks. There is only one thing bugging me:
It seems to me that the "one button to push" has been working for most users so far, replacing that one button with a "push a button -> select from dropdown -> push another button" could get annoying in comparison. 
Maybe I am just overthinking this issue a bit, but I will ask some more people before merging this feature.

**Comment by nounoursheureux** [comment]
Yeah, I understand. Maybe we can make it optionnal, and stay with the "one-click-to-push" behaviour by default.

**Comment by MarcelMue** [comment]
I was thinking the same thing, but I can't think of a good way to do it in git-controls interface right now :/

**Comment by MarcelMue** [comment]
Your latest commit and some discussion fixed my concerns. I have only briefly tested this change now and will do so more before the next release. I will merge this fork for now and hope that it will work nicely.

Thanks for your contribution once again!
:+1:

**Pull request merged**
