### PR TITLE
Colour commit text when characters exceed 50

### PR DESCRIPTION
**Pull request by Otterpocket**
I found this feature quite helpful whilst using the git plus package. So I thought I would have a go at implementing it in git-control.

### CODE REVIEW

**Comment by MarcelMue** [comment]
I agree that this is a good change but I have a minor issue with it:
You change the color in an RGB value, this might cause problems with different themes in Atom. I would favor it if `@text-color-error` was used. 
The best way to do this as far as I can tell is to add something like
`.warning {
   color: @text-color-error
  }`
to the `dialog.less` and then add and remove it like so:
  `colorLength: ->
    if @msg.val().length > 50
      @msg.addClass('warning')
    else
      @msg.removeClass('warning')`
Please let me know if you agree with this or if you have a better suggestion!

**Comment by Otterpocket** [comment]
Yes this did cross my mind, I think I went against doing like that because I didn't want to class it as an error or warning, but in retrospect I think that having it follow the the theme is a better way to do it. Ill change it and the re-commit.

Thanks

**Comment by MarcelMue** [comment]
Sounds good to me :+1:

**Comment by MarcelMue** [comment]
Thanks for the contribution :+1:

**Pull request merged**
