### PR TITLE
Changes to include submodule support

### LINKED ISSUE #31: Add support for submodules
It should be able to notice when in a submodule and pull up the repo for that submodule.   Either that or expand submodules and allow you to commit to them too.

### PR DESCRIPTION
**Pull request by SerenadeX**
Should partially fix #31.  Won't handle if a submodule is inside the root of the project but only if the submodule is the root of the project.

### CODE REVIEW

**Comment by SerenadeX** [comment]
PING! YAY! 😂

**Comment by internalfx** [comment]
Pingity Ping!

@SerenadeX Fork? I was interested in contributing to this. But I see you are a few commits ahead...

**Comment by SerenadeX** [comment]
Well I already made a fork and did the work...

**Comment by internalfx** [comment]
Right, but your fork isn't a separate project, so no issues...and stuff...

**Comment by SerenadeX** [comment]
Well if there are issues make them known here. I didn't change that much.

**Comment by internalfx** [comment]
ok ok...I'll drop it. I hope something eventually gets merged.

**Comment by SerenadeX** [comment]
Ha I really don't care.  I can make a whole different project.  I just thought since I only changed 15 lines that doing it this way was efficient enough

**Comment by internalfx** [comment]
Us js devs have no problem, sure. But I know this package is used by lots of designers. They are stuck with whatever the atom installer gives them. Perhaps it would be best if @jacogr was willing to add a contributor to help with the project.

**Comment by SerenadeX** [comment]
Well you guys let me know how you want me to do it.  I am just giving a helping hand 😊

**Comment by MarcelMue** [comment]
I am going to play with this myself, but I think only merging in submodules if they are the root of the project is not very clean.

**Comment by MarcelMue** [comment]
Closed due to inactivity.

**Pull request closed without merging**
