### PR TITLE
Added the no-ff option

### PR DESCRIPTION
**Pull request by nounoursheureux**
First time using Less and the Atom views so I may have done something wrong :P
#34

### CODE REVIEW

**Comment by MarcelMue** [comment]
Looks solid so far, I will try it out later today!

**Comment by MarcelMue** [comment]
Okay I had a look at everything and only have two minor nitpicks:
- The checkbox is not aligned with the text (might be an issue with my theme maybe). Not really critical but looks a bit silly :P 
- In `git.coffee` you use both `noff`and `noFF`. I think it wouldn't hurt to be a bit more descriptive here and call `noFF` something like `noffOutput` to prevent confusion. 

Great addition all in all, once again these are just very minor issues :)

**Comment by nounoursheureux** [comment]
Thanks for the review :) . `vertical-align: middle` didn't work so I had to set it manually

**Comment by MarcelMue** [comment]
Looks fine now, thanks once again for the contribution :+1:

**Pull request merged**
